namespace Warcraft.Abilities.Game;

/// <summary>Colour families of the particle library (PALETTE in assets/tools/make_particles.py).</summary>
internal enum FxColor
{
    Heal,
    Fire,
    Frost,
    Holy,
    War,
    Storm,
    Blood,
    Poison,
    Arcane,
    Shadow,
    Nature
}

/// <summary>
/// Particle systems shipped in the Warcraft UI Workshop addon (generated by
/// assets/tools/make_particles.py, compiled by src/Warcraft.Menu/hud/build.ps1).
/// Every archetype exists in every <see cref="FxColor"/>. Precached on map load.
/// </summary>
internal static class WarcraftParticles
{
    private const string Root = "particles/warcraft/";

    /// <summary>Ring of fire tongues and embers around the feet (immolation).</summary>
    public const string FlamesRing = Root + "flames_ring.vpcf";

    /// <summary>Small fire on a point (flame totem bowl).</summary>
    public const string FlamesBrazier = Root + "flames_brazier.vpcf";

    /// <summary>Red flames and embers around a raging player.</summary>
    public const string FlamesRage = Root + "flames_rage.vpcf";

    /// <summary>Snow falling around a point with frost motes (frost totem).</summary>
    public const string Snow = Root + "snow.vpcf";

    private static readonly string[] Specials = [FlamesRing, FlamesBrazier, FlamesRage, Snow];

    private static readonly string[] Archetypes =
        ["flash", "motes", "body", "burst", "nova", "column", "line", "radius", "sparks", "smoke"];

    // Child systems referenced by the archetypes above.
    private static readonly string[] Children = ["motes_{0}_wisps", "body_{0}_glow", "nova_{0}_dust", "line_{0}_glow"];

    /// <summary>Single bright glow.</summary>
    public static string Flash(FxColor color) => Path("flash", color);

    /// <summary>Loop: motes rising from a ring at the feet (auras, totems).</summary>
    public static string Motes(FxColor color) => Path("motes", color);

    /// <summary>Loop: particles swirling around a player's body (buffs, debuffs).</summary>
    public static string Body(FxColor color) => Path("body", color);

    /// <summary>One-shot sparkle explosion.</summary>
    public static string Burst(FxColor color) => Path("burst", color);

    /// <summary>One-shot glowing shockwave and dust racing along the ground.</summary>
    public static string Nova(FxColor color) => Path("nova", color);

    /// <summary>One-shot pillar of light rising from the ground.</summary>
    public static string Column(FxColor color) => Path("column", color);

    /// <summary>Ray from the entity to control point 1 (lightning for <see cref="FxColor.Storm"/>).</summary>
    public static string Line(FxColor color) => Path("line", color);

    /// <summary>Loop: shimmering circle whose radius is control point 1's X.</summary>
    public static string Radius(FxColor color) => Path("radius", color);

    /// <summary>One-shot hot sparks (impacts).</summary>
    public static string Sparks(FxColor color) => Path("sparks", color);

    /// <summary>One-shot smoke puff.</summary>
    public static string Smoke(FxColor color) => Path("smoke", color);

    public static IReadOnlyList<string> All { get; } =
    [
        .. Specials,
        .. Enum.GetValues<FxColor>().SelectMany(color => Archetypes.Select(kind => Path(kind, color))),
        .. Enum.GetValues<FxColor>().SelectMany(color => Children.Select(child =>
            Root + string.Format(child, Name(color)) + ".vpcf"))
    ];

    private static string Path(string kind, FxColor color) => $"{Root}{kind}_{Name(color)}.vpcf";

    private static string Name(FxColor color) => color.ToString().ToLowerInvariant();
}
