"""Build the CS2Warcraft model sources under assets/addon/ (content root of the addon).

- Meshy models (OBJ + base color PNG) are centered, placed on the ground and
  scaled to a target size in game units. OBJ stays Y-up: ModelDoc imports OBJ
  as engine (x, y, z) = obj (z, x, y), verified with a compiled test box.
- Procedural glow meshes (aura ring, shield bubble) and their textures are generated.
- ModelDoc .vmdl and .vmat files are written next to each mesh.

Usage: python prepare_models.py <meshy_out_dir>
"""
import math
import os
import sys

from pngutil import downscale_png, write_png

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "addon"))

# name: (group, size in game units, measured axis in OBJ space: "height" = Y, "width" = max(X, Z))
# Models whose generated shape is standing although it must lie on the ground (rotated -90 deg about X).
LAY_FLAT = {"entangle_roots"}
MESHY_MODELS = {
    "totem_healing": ("totems", 64.0, "height"),
    "totem_flame": ("totems", 64.0, "height"),
    "totem_frost": ("totems", 64.0, "height"),
    "totem_war": ("totems", 64.0, "height"),
    "totem_shield": ("totems", 64.0, "height"),
    "entangle_roots": ("effects", 72.0, "width"),
}

VMDL = """<!-- kv3 encoding:text:version{{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d}} format:modeldoc41:version{{12fc9d44-453a-4ae4-b4d9-7e2ac0bbd4e0}} -->
{{
	rootNode =
	{{
		_class = "RootNode"
		children =
		[
			{{
				_class = "MaterialGroupList"
				children =
				[
					{{
						_class = "DefaultMaterialGroup"
						remaps =
						[
							{{
								from = "{name}.vmat"
								to = "{path}/{name}.vmat"
							}},
						]
						use_global_default = true
						global_default_material = "{path}/{name}.vmat"
					}},
				]
			}},
			{{
				_class = "RenderMeshList"
				children =
				[
					{{
						_class = "RenderMeshFile"
						filename = "{path}/{name}.obj"
						import_scale = 1.0
						import_filter =
						{{
							exclude_by_default = false
							exception_list = [ ]
						}}
					}},
				]
			}},
		]
		model_archetype = ""
		primary_associated_entity = ""
		document_sub_type = "ModelDocSubType_None"
	}}
}}
"""

OPAQUE_VMAT = """// Generated by assets/tools/prepare_models.py

Layer0
{{
	shader "csgo_complex.vfx"
	g_flMetalness "0.000"
	g_flModelTintAmount "1.000"
	g_vColorTint "[1.000000 1.000000 1.000000 0.000000]"
	TextureColor "{path}/{name}_color.png"
}}
"""

# Translucent, tintable (entity render color) and self-illuminated so it reads as a glow at night.
GLOW_VMAT = """// Generated by assets/tools/prepare_models.py

Layer0
{{
	shader "csgo_complex.vfx"
	F_TRANSLUCENT "1"
	F_SELF_ILLUM "1"
	g_flMetalness "0.000"
	g_flModelTintAmount "1.000"
	g_flOpacityScale "1.000"
	g_flSelfIllumBrightness "2.000"
	g_vColorTint "[1.000000 1.000000 1.000000 1.000000]"
	TextureColor "{path}/{name}_color.png"
	TextureTranslucency "{path}/{name}_trans.png"
	TextureSelfIllumMask "{path}/{name}_trans.png"
}}
"""


def model_dir(group, name):
    path = f"models/warcraft/{group}/{name}"
    directory = os.path.join(ROOT, *path.split("/"))
    os.makedirs(directory, exist_ok=True)
    return path, directory


def write_model_files(group, name, vmat_template):
    path, directory = model_dir(group, name)
    with open(os.path.join(directory, f"{name}.vmdl"), "w", encoding="utf-8", newline="\n") as f:
        f.write(VMDL.format(name=name, path=path))
    with open(os.path.join(directory, f"{name}.vmat"), "w", encoding="utf-8", newline="\n") as f:
        f.write(vmat_template.format(name=name, path=path))
    return directory


def lay_flat(line, prefix):
    x, y, z = map(float, line.split()[1:4])
    return f"{prefix} {x} {z} {-y}"


def normalize_obj(source, target, name, size, measure):
    lines = open(source, encoding="utf-8", errors="ignore").read().splitlines()
    if name in LAY_FLAT:
        lines = [lay_flat(line, "v") if line.startswith("v ") else
                 lay_flat(line, "vn") if line.startswith("vn ") else line
                 for line in lines]
    vertices = [tuple(map(float, line.split()[1:4])) for line in lines if line.startswith("v ")]
    lo = [min(v[i] for v in vertices) for i in range(3)]
    hi = [max(v[i] for v in vertices) for i in range(3)]
    extent = hi[1] - lo[1] if measure == "height" else max(hi[0] - lo[0], hi[2] - lo[2])
    scale = size / extent
    cx, cz = (lo[0] + hi[0]) / 2, (lo[2] + hi[2]) / 2

    out = [f"# {name}: normalized for CS2Warcraft (Y-up, ground at y=0, scale {scale:.4f})", f"o {name}"]
    for line in lines:
        if line.startswith("v "):
            x, y, z = map(float, line.split()[1:4])
            out.append(f"v {(x - cx) * scale:.4f} {(y - lo[1]) * scale:.4f} {(z - cz) * scale:.4f}")
        elif line.startswith(("vt ", "vn ", "f ")):
            if line.startswith("f ") and f"usemtl {name}" not in out:
                out.append(f"usemtl {name}")
            out.append(line)
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return [round((hi[i] - lo[i]) * scale, 1) for i in range(3)]


def build_meshy(meshy_dir):
    for name, (group, size, measure) in MESHY_MODELS.items():
        source = os.path.join(meshy_dir, name)
        directory = write_model_files(group, name, OPAQUE_VMAT)
        dims = normalize_obj(os.path.join(source, "model.obj"), os.path.join(directory, f"{name}.obj"), name, size, measure)
        # Meshy delivers 2048px atlases; 1024px is plenty for props of this size.
        downscale_png(os.path.join(source, "texture.png"), os.path.join(directory, f"{name}_color.png"))
        print(f"{group}/{name}: {dims} units")


def write_obj(path, name, vertices, uvs, faces):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"# {name}: generated by prepare_models.py\no {name}\n")
        for v in vertices:
            f.write("v %.4f %.4f %.4f\n" % v)
        for t in uvs:
            f.write("vt %.4f %.4f\n" % t)
        f.write(f"usemtl {name}\n")
        for a, b, c in faces:
            f.write(f"f {a + 1}/{a + 1} {b + 1}/{b + 1} {c + 1}/{c + 1}\n")


def glow_texture(directory, name, size, alpha_at):
    """White color map + grayscale translucency/self-illum mask from alpha_at(u, v) in 0..1."""
    color = bytearray()
    mask = bytearray()
    for y in range(size):
        for x in range(size):
            a = max(0.0, min(1.0, alpha_at((x + 0.5) / size, (y + 0.5) / size)))
            color += bytes((255, 255, 255))
            mask += bytes((int(a * 255),) * 3)
    write_png(os.path.join(directory, f"{name}_color.png"), size, size, color, channels=3)
    write_png(os.path.join(directory, f"{name}_trans.png"), size, size, mask, channels=3)


def build_aura_ring():
    """Flat ring lying on the ground (OBJ y = up), radius 48 units, double-sided."""
    name, group, segments = "aura_ring", "effects", 48
    inner, outer, lift = 34.0, 48.0, 1.5
    directory = write_model_files(group, name, GLOW_VMAT)
    vertices, uvs, faces = [], [], []
    for i in range(segments + 1):
        angle = 2 * math.pi * i / segments
        for radius, v in ((inner, 0.0), (outer, 1.0)):
            vertices.append((math.cos(angle) * radius, lift, math.sin(angle) * radius))
            uvs.append((i / segments, v))
    for i in range(segments):
        a, b, c, d = 2 * i, 2 * i + 1, 2 * i + 2, 2 * i + 3
        faces += [(a, b, d), (a, d, c), (a, d, b), (a, c, d)]  # both windings: visible from above and below
    write_obj(os.path.join(directory, f"{name}.obj"), name, vertices, uvs, faces)
    # Bright core line with soft falloff across the ring width (texture V).
    glow_texture(directory, name, 64, lambda u, v: math.exp(-((v - 0.55) / 0.22) ** 2))
    print(f"{group}/{name}: ring r={inner}..{outer}")


def build_shield_bubble():
    """UV sphere around a standing player: radius 42, centered 38 units above the ground."""
    name, group = "shield_bubble", "effects"
    radius, center, rings, sectors = 42.0, 38.0, 16, 32
    directory = write_model_files(group, name, GLOW_VMAT)
    vertices, uvs, faces = [], [], []
    for r in range(rings + 1):
        phi = math.pi * r / rings
        for s in range(sectors + 1):
            theta = 2 * math.pi * s / sectors
            vertices.append((
                math.sin(phi) * math.cos(theta) * radius,
                center + math.cos(phi) * radius,
                math.sin(phi) * math.sin(theta) * radius))
            uvs.append((s / sectors, r / rings))
    for r in range(rings):
        for s in range(sectors):
            a = r * (sectors + 1) + s
            b = a + sectors + 1
            faces += [(a, b, a + 1), (a + 1, b, b + 1)]
    write_obj(os.path.join(directory, f"{name}.obj"), name, vertices, uvs, faces)
    # Faint body with brighter horizontal bands, like a hex/energy shell.
    glow_texture(directory, name, 128, lambda u, v: 0.18 + 0.35 * (math.sin(v * math.pi * 12) ** 8))
    print(f"{group}/{name}: sphere r={radius}")


def main():
    build_meshy(sys.argv[1])
    build_aura_ring()
    build_shield_bubble()


if __name__ == "__main__":
    main()
